#@ load("@ytt:data", "data")
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deliverable-role
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
      - serving.knative.dev
      - ""
    resources:
      - gitrepositories
      - services
      - configmaps
    verbs:
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deliverable-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deliverable-role
subjects:
  - kind: ServiceAccount
    name: #@ data.values.service_account.name
    namespace: #@ data.values.service_account.namespace