apiVersion: v1
kind: Secret
metadata:
  name: <GITOPS-SECRET-NAME>
  annotations:
    tekton.dev/git-0: <GIT_SERVER_HOST>        # ! required
type: kubernetes.io/basic-auth          # ! required
stringData:
  username: <GITOPS_GIT_USERNAME>
  password: <GITOPS_GIT_PASSWORD>