---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demoapp
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: demoapp
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/YOURINPUT-GITUSERNAME/YOURINPUT-GIT-SOURCE-CODE-REPO
  params:
    - name: testing_pipeline_matching_labels # multi-pipeline functionality
      value: '{"apps.tanzu.vmware.com/pipeline":"test", "apps.tanzu.vmware.com/language":"java"}' # multi-pipeline functionality
    - name: gitops_ssh_secret
      value: git-ssh
    - name: gitops_server_address
      value: https://github.com/
    - name: gitops_repository_owner
      value: YOURINPUT-GITOPS-WRITE-USERNAME
    - name: gitops_repository_name
      value: YOURINPUT-GITOPS-WRITE-REPO

# tanzu apps workload create demoapp \
#   --git-repo https://github.com/alinahid477/demo-app-sc \
#   --git-branch main \
#   --type web \
#   --build-env BP_JVM_VERSION=17 \
#   --label app.kubernetes.io/part-of=springboot-maven \
#   --label apps.tanzu.vmware.com/has-tests=true \
#   --param-yaml testing_pipeline_matching_labels='{"apps.tanzu.vmware.com/pipeline":"test", "apps.tanzu.vmware.com/language":"java"}'
#   --annotation autoscaling.knative.dev/minScale=1 \
#   --namespace default \
#   --tail \
#   --yes