---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demoapp
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: demoapp
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/alinahid477/demo-app-sc