---
apiVersion: v1
kind: Namespace
metadata:
  name: external-resources-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: db-access-secret
  namespace: external-resources-secrets
type: Opaque
stringData:
  type: postgresql
  provider: elephantsql
  url: "r2dbc:postgres://aqyqfuxg:sm_efk_LoZn8xK7VbU76bHPWOSZp-M1Z@rosie.db.elephantsql.com/aqyqfuxg"
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: db-secret-cross-namespace
  namespace: external-resources-secrets
spec:
  consumingNamespaces:
  - '*'
  subject:
    group: ""
    kind: Secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stk-secret-reader
  labels:
    servicebinding.io/controller: "true"
    resourceclaims.services.apps.tanzu.vmware.com/controller: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: db-access-secret-resource-claim
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: db-access-secret
    namespace: external-resources-secrets
