profile: full

shared:
  ingress_domain: "YOURINPUT_INGRESS_DOMAIN" # eg: tap.corp.tanzu
  image_registry:
    project_path: "YOURINPUT.azurecr.io/myimages"
    secret:
      name: TARGET_REGISTRY_CREDENTIALS_SECRET_NAME
      namespace: tap-install

ceip_policy_disclosed: true

metadata_store:
  app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
  ns_for_export_app_cert: "*"
buildservice:
  kp_default_repository: "YOURINPUT.azurecr.io/build-service"
  kp_default_repository_secret:
    name: TARGET_REGISTRY_CREDENTIALS_SECRET_NAME
    namespace: tap-install
  include_legacy_bom: false
  exclude_dependencies: true

scanning:
  metadataStore:
    url: ""

contour:
  envoy:
    service:
      type: LoadBalancer

grype:
  namespace: NAMESPACE_WHERE_SCANNING_WILL_RUN
  targetImagePullSecret: TARGET_REGISTRY_CREDENTIALS_SECRET_NAME

supply_chain: testing_scanning

ootb_supply_chain_testing_scanning:
  registry:
    server: "YOURINPUT.azurecr.io"
    repository: "projects"
  gitops:
    server_address: https://github.com
    repository_owner: YOURINPUT
    repository_name: https://github.com/YOURINPUT/gitops-repo
    branch: "main"
    user_name: "YOURINPUTNotRealUser"
    user_email: "YOURINPUTNotRealUser@cluster.local"
    commit_message: "tap-demo-commit-from-YOURINPUTNotRealUser"
    ssh_secret: "GIT_SSH_SECRET"
    commit_strategy: direct
  scanning:
    source:
      policy: scan-policy
      template: blob-source-scan-template
    image:
      policy: scan-policy
      template: private-image-scan-template
  cluster_builder: default
  service_account: default

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "YOURINPUT_INGRESS_DOMAIN" # eg: tap.corp.tanzu
  app_config:
    proxy:
      /metadata-store:
        target: https://metadata-store-app.metadata-store:8443/api/v1
        changeOrigin: true
        secure: false
        headers:
          Authorization: "Bearer TAPGUI_READONLY_CLIENT_SA_TOKEN" # No need to change TAPGUI_READONLY_CLIENT_SA_TOKEN. Replace is automate in merlin script. If not changed Merlin will auto detect this variable and deploy appropriate Service Account and replace TAPGUI_READONLY_CLIENT_SA_TOKEN with access token of the sercice account.
          X-Custom-Source: project-star
    app:
      baseUrl: http://tap-gui.YOURINPUT_INGRESS_DOMAIN #eg: http://tap-gui.tap.corp.tanzu
    catalog:
      locations:
        - type: url
          target: https://github.com/YOURINPUT/tap-gui/blob/main/blank/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.YOURINPUT_INGRESS_DOMAIN
      cors:
        origin: http://tap-gui.YOURINPUT_INGRESS_DOMAIN

cnrs:
  domain_name: apps.YOURINPUT_INGRESS_DOMAIN # eg: apps.tap.corp.tanzu
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

excluded_packages:
  - policy.apps.tanzu.vmware.com
  - image-policy-webhook.signing.apps.tanzu.vmware.com
  - learningcenter.tanzu.vmware.com
  - workshops.learningcenter.tanzu.vmware.com