profile: full

shared:
  ingress_domain: "tap.corp.tanzu"
  image_registry:
    project_path: "YOURINPUT.azurecr.io/projects"
    username: "YOURINPUT_USERNAME"
    password: "YOURINPUT_PASSWORD"

ceip_policy_disclosed: true 

metadata_store:
  app_service_type: ClusterIP # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer
  ns_for_export_app_cert: "*"
buildservice:
  kp_default_repository: "YOURINPUT.azurecr.io/build-service"
  kp_default_repository_username: "YOURINPUT_USERNAME"
  kp_default_repository_password: "YOURINPUT_PASSWORD"


contour:
  envoy:
    service:
      type: LoadBalancer

grype:
  namespace: "default" # (optional) Defaults to default namespace.
  targetImagePullSecret: "registry-credentials"

scanning:
  metadataStore:
    url: "" # Disable embedded integration since it's deprecated
  source:
    policy: scan-policy
    template: blob-source-scan-template
  image:
    policy: scan-policy
    template: private-image-scan-template


supply_chain: testing_scanning

ootb_supply_chain_testing_scanning:
  registry:
    server: "YOURINPUT.azurecr.io"
    repository: "projects"
  gitops:
    server_address: https://github.com
    repository_owner: YOUTUNPUT_REPO_USERNAME
    repository_name: https://github.com/YOURINPUTREPO_USERNAME/tapdemo-gitops
    branch: "main"
    user_name: "dc3tap1"
    user_email: "dc3tap1@cluster.local"
    commit_message: "tap-demo-commit-from-dctap1"
    ssh_secret: "git-ssh"
    commit_strategy: direct
  cluster_builder: default
  service_account: default


  

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "tap.corp.tanzu"
  app_config:
    integrations:
      github:
        - host: github.com
          token: "YOURINPUT_GITHUBTOKEN"
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: YOURINPUT_GITHUB_APP_CLIENT_ID
            clientSecret: YOURINPUT_GITHUB_APP_CLIENT_SECRET
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
          - url: https://YOUINPUT_URL_OR_IP:6443
            name: dc3taprun
            authProvider: serviceAccount
            serviceAccountToken: "YOURINPUT_SVC_ACC_TOKEN"
            skipTLSVerify: true
            skipMetricsLookup: true
          - url: https://YOUINPUT_URL_OR_IP:6443
            name: dc3tap2
            authProvider: serviceAccount
            serviceAccountToken: "YOURINPUT_SVC_ACC_TOKEN"
            skipTLSVerify: true
            skipMetricsLookup: true
    proxy:
      /metadata-store:
        target: https://metadata-store-app.metadata-store:8443/api/v1
        changeOrigin: true
        secure: false
        headers:
          Authorization: "Bearer SVC_ACCOUNT_TOKEN"
          X-Custom-Source: project-star
    app:
      baseUrl: http://tap-gui.tap.corp.tanzu
    catalog:
      locations:
        - type: url
          target: https://github.com/YOURINPUTREPOUSERNAME/tap-gui/blob/main/blank/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.tap.corp.tanzu
      cors:
        origin: http://tap-gui.tap.corp.tanzu

cnrs:
  domain_name: apps.tap.corp.tanzu
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"

appliveview:
 ingressEnabled: true
 sslDisabled: true

excluded_packages: 
  - policy.apps.tanzu.vmware.com
  - image-policy-webhook.signing.apps.tanzu.vmware.com
  - learningcenter.tanzu.vmware.com
  - workshops.learningcenter.tanzu.vmware.com


